### ISSUE TITLE
Apply transformations from model.json

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/coda#4]
Would it be helpful to add a method to applies transformations from a BIDS model.json file? In the nipype pull request, looping over steps is done in the code for the interface. @tyarkoni ?

Caveat: BIDS model spec is not complete, although transformation spec seems unlikely to have major changes.

**Comment by tyarkoni** [comment]
Yes, I think that's probably the way to go. There is one potential drawback, which is that this would basically commit us to keeping this method in sync with the BIDS-model spec forever. But since we would need to update the Nipype interface to do that otherwise, and since users are only going to be calling this method if they're already aware of the BIDS-model spec, I don't see a big reason not to handle json transformations inside coda itself. The advantage is then that users can make use of the json model spec even if they're not interested in committing to using Nipype.

**Comment by adelavega** [comment]
I agree. I mean we're already committed to keeping this in sync w/ the BIDS-model spec, since it specifies which transformations you can apply, and what they're called. Might as well centralize the code that needs to be kept in sync w/ BIDS-model in one place.
